#  大小写敏感
#  使用缩进表示层级关系 
#  缩进时【不允许使用Tab键】，只允许使用空格 
#  缩进的空格数目不重要，只要相同层级的元素左侧对齐即可

# 选择运行环境  -dev 开发环境(对应的是application-dev.yml文件)     -prod 线上环境(对应的是application-prod.yml文件)   
spring:
  profiles:
    active:
    - dev